### ISSUE TITLE
Hello my buddy,I just got in trouble,chould u help me?

### ISSUE THREAD

**Issue by Hushabyme** [digitalcraftsman/hugo-steam-theme#12]
I use your theme,it's amaing!
I really like this style! but there's some trouble to me. I can't built the main page like you.How it's going?
there it's yours:http://themes.gohugo.io/theme/steam/
and there is mine,it's look like some weird... : https://hushabyme.github.io/
could you teach me how to build like yours?
I appreciate it if it could be solved.

**Comment by digitalcraftsman** [comment]
Hello @Hushabyme,

it's hard to tell without having the original setup of your page. The reason might be that the homepage just showed pages of type post, i.e. those files located in `content/post`, and you used a different subdirectory.

However, I revised the whole theme and removed this limitation. For more information have a look at the [changelog](https://github.com/digitalcraftsman/hugo-steam-theme/blob/master/CHANGELOG.md).

Please update your theme to the latest version and let me know if this issue is still present. Otherwise upload the source files for your Hugo website (not the generated HTML) in a temporary repository on GitHub and link it in your answer.

**Comment by Hushabyme** [comment]
Thank you for your answer!
I will read your advice and reference carefully,and there has another question,this is my first use the hugo to set my blog.how to refresh the the article on my homepage,(now,I have exist the blog on github pages)using git orders or something else?

**Comment by digitalcraftsman** [comment]
> how to refresh the the article on my homepage,(now,I have exist the blog on github pages)using git orders or something else?

What do you mean with github orders? To update a website on GitHub pages you usually do it as follows:

1. you make some changes
2. you generate your site again with the `hugo` command
3. you create a new commit
4. you push all changes to https://github.com/Hushabyme/Hushabyme.github.io

You can also automate this with external services that rebuild your pages once a new commit has been pushed to a repository. Have a look at [this tutorial](https://gohugo.io/tutorials/automated-deployments/).

**Comment by Hushabyme** [comment]
Wow,it's so kind of you!
the git order...ohhh... I mean the Git,the syntax like that $git.
sorry,Im a student in China,so my English is not well.Some words are not standard.
anyway,thank you for your help,wish you work better and better!

**Comment by digitalcraftsman** [comment]
> sorry,Im a student in China,so my English is not well.Some words are not standard. anyway,thank you for your help,wish you work better and better!

No problem. Please close this issue if your problems are gone.

Cheers,
Digitalcraftsman

**Comment by Hushabyme** [comment]
Cheers!
